# Prometheus scrape config for RabbitMQ
# Add this to your prometheus.yml scrape_configs section

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['localhost:15692']
        labels:
          service: 'c3l-rabbitmq'
          environment: 'development'
    
    scrape_interval: 15s
    scrape_timeout: 10s
    
    # Optional: Basic auth if configured
    # basic_auth:
    #   username: 'prometheus'
    #   password: '<password>'
    
    # Relabeling for better metric organization
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rabbitmq_.*'
        action: keep

  # Optional: NATS monitoring (requires NATS with monitoring enabled)
  # - job_name: 'nats'
  #   static_configs:
  #     - targets: ['localhost:8222']
  #       labels:
  #         service: 'c3l-nats'
  #         environment: 'development'
  #   scrape_interval: 15s

