apiVersion: apps/v1
kind: Deployment
metadata:
  name: psi-field
  labels:
    app: psi-field
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psi-field
  template:
    metadata:
      labels:
        app: psi-field
    spec:
      containers:
      - name: psi-field
        image: 509399262563.dkr.ecr.eu-west-1.amazonaws.com/vaultmesh/psi-field@sha256:531f69f4b71a2d212713612753a86e739df42e0cccc5e7b79c023599ac83b7f4
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: remembrancer-volume
          mountPath: /app/ops
      volumes:
      - name: remembrancer-volume
        persistentVolumeClaim:
          claimName: remembrancer-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: psi-field
spec:
  selector:
    app: psi-field
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
