[package]
name = "vm-receipt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
hex.workspace = true
