apiVersion: v1
kind: Service
metadata:
  name: aurora-intelligence
  namespace: vaultmesh
  labels:
    app: aurora-intelligence
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: aurora-intelligence
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
