apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aurora-router
  labels:
    app: aurora-router
    component: routing
spec:
  selector:
    matchLabels:
      app: aurora-router
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
