name: repo-audit
on:
  push: { branches: ["main"] }
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: read
  security-events: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install audit tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit cyclonedx-bom coverage pytest rich pygount tomli

      - name: Run repo audit (best effort; never fail)
        run: |
          python scripts/repo_audit.py > vm-spawn-audit.md || true
          echo "## vm-spawn — Audit Summary" >> $GITHUB_STEP_SUMMARY
          sed -n '1,200p' vm-spawn-audit.md >> $GITHUB_STEP_SUMMARY || true

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: vm-spawn-audit-${{ github.sha }}
          path: vm-spawn-audit.md
