name: Transparency Receipts Site

on:
  workflow_dispatch:
  schedule:
    - cron: "17 2 * * *"
  push:
    branches: [ main ]
    paths:
      - 'ops/receipts/**'
      - 'ops/bin/receipts-site'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate receipts index
        run: |
          ./ops/bin/receipts-site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

