name: Rust CI (v5.0 Scaffold)

on:
  push:
    branches: ["**"]
    paths:
      - "v4.5-scaffold/**"
      - "rust-toolchain.toml"
      - ".github/workflows/rust-ci.yml"
  pull_request:
    paths:
      - "v4.5-scaffold/**"
      - "rust-toolchain.toml"
      - ".github/workflows/rust-ci.yml"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Gate: Format & Lint
  check:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"
          components: clippy, rustfmt
          cache: false

      - name: Install deps (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsqlite3-dev nettle-dev libgmp-dev clang llvm-dev

      - name: Check formatting
        working-directory: v4.5-scaffold
        run: cargo fmt --all -- --check

      - name: Clippy (all features)
        working-directory: v4.5-scaffold
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  # Gate: Build & Test
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            features: "--all-features"
          - os: macos-latest
            features: "--all-features"
          - os: windows-latest
            features: "--no-default-features --features vm-cli/sqlite,vm-cli/tls-rustls"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"
          components: clippy, rustfmt
          cache: false

      - name: Install deps (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsqlite3-dev nettle-dev libgmp-dev clang llvm-dev

      - name: Install deps (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install pkg-config sqlite nettle gmp

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Build workspace
        working-directory: v4.5-scaffold
        run: cargo build --workspace ${{ matrix.features }}

      - name: Run tests (nextest)
        working-directory: v4.5-scaffold
        run: cargo nextest run --workspace ${{ matrix.features }} --no-fail-fast

      - name: Run doctests
        working-directory: v4.5-scaffold
        run: cargo test --doc --workspace ${{ matrix.features }}

  # Gate: Property & Fuzz Tests
  extended-tests:
    name: Property & Fuzz Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"

      - name: Install deps (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsqlite3-dev nettle-dev libgmp-dev

      - name: Install cargo-fuzz
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-fuzz

      - name: Run property tests
        working-directory: v4.5-scaffold
        run: cargo test --workspace --all-features --release -- --ignored proptest

      - name: Fuzz receipt parser (60s smoke)
        working-directory: v4.5-scaffold/fuzz
        run: |
          cargo fuzz build receipt_parse
          timeout 60 cargo fuzz run receipt_parse -- -max_total_time=60 || true

  # Gate: Security & Supply Chain
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"

      - name: Run cargo-deny (advisories, licenses, sources)
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          arguments: --workspace --all-features
          manifest-path: v4.5-scaffold/Cargo.toml

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'v4.5-scaffold'
          format: 'table'
          exit-code: '0'  # Permissive for now; tighten in v5.1
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  # Gate: Coverage
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"

      - name: Install deps (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsqlite3-dev nettle-dev libgmp-dev

      - name: Install tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Generate coverage
        working-directory: v4.5-scaffold
        run: cargo tarpaulin --workspace --all-features --out Lcov --output-dir ../coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          fail_ci_if_error: false

  # Release: Build artifacts (on tags)
  release:
    name: Release Build (${{ matrix.target }})
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write  # For SLSA attestations
      attestations: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: vm-cli-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact: vm-cli-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: vm-cli-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: vm-cli-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: vm-cli-windows-amd64.exe
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.85.0"
          target: ${{ matrix.target }}

      - name: Install deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libsqlite3-dev nettle-dev libgmp-dev clang llvm-dev

      - name: Build release binary
        working-directory: v4.5-scaffold
        run: cargo build --release --target ${{ matrix.target }} -p vm-cli

      - name: Prepare artifact
        id: prep
        shell: bash
        run: |
          BINARY_PATH="v4.5-scaffold/target/${{ matrix.target }}/release/vm-cli${{ matrix.os == 'windows-latest' && '.exe' || '' }}"
          echo "binary_path=${BINARY_PATH}" >> "$GITHUB_OUTPUT"
          # Compute SHA256 for attestation
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            sha256sum "${BINARY_PATH}" | awk '{print $1}' > "${BINARY_PATH}.sha256"
          else
            shasum -a 256 "${BINARY_PATH}" | awk '{print $1}' > "${BINARY_PATH}.sha256"
          fi
          echo "sha256=$(cat ${BINARY_PATH}.sha256)" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            ${{ steps.prep.outputs.binary_path }}
            ${{ steps.prep.outputs.binary_path }}.sha256

      - name: Attest build provenance (SLSA)
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ steps.prep.outputs.binary_path }}

      - name: Install cosign (optional keyless signing)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: sigstore/cosign-installer@v3

      - name: Sign binary with cosign (keyless)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          COSIGN_YES: "true"
        run: |
          cosign sign-blob --yes \
            --bundle ${{ steps.prep.outputs.binary_path }}.cosign-bundle \
            ${{ steps.prep.outputs.binary_path }}

      - name: Upload cosign bundle
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}-cosign-bundle
          path: ${{ steps.prep.outputs.binary_path }}.cosign-bundle
